package net.swiftzer.etademo.common

import androidx.annotation.Keep

@Keep
enum class Station(val zh: String, val en: String) {
    UNKNOWN("", ""),

    HOK("香港", "Hong Kong"),
    KOW("九龍", "Kowloon"),
    OLY("奧運", "Olympic"),
    NAC("南昌", "Nam Cheong"),
    LAK("茘景", "Lai King"),
    TSY("青衣", "Tsing Yi"),
    SUN("欣澳", "Sunny Bay"),
    TUC("東涌", "Tung Chung"),
    AIR("機場", "Airport"),
    AWE("博覽館", "AsiaWorld-Expo"),

    WKS("烏溪沙", "Wu Kai Sha"),
    MOS("馬鞍山", "Ma On Shan"),
    HEO("恆安", "Heng On"),
    TSH("大水坑", "Tai Shui Hang"),
    SHM("石門", "Shek Mun"),
    CIO("第一城", "City One"),
    STW("沙田圍", "Sha Tin Wai"),
    CKT("車公廟", "Che Kung Temple"),
    TAW("大圍", "Tai Wai"),
    HIK("顯徑", "Hin Keng"),
    DIH("鑽石山", "Diamond Hill"),
    KAT("啟德", "Kai Tak"),
    SUW("宋皇臺", "Sung Wong Toi"),
    TKW("土瓜灣", "To Kwa Wan"),
    HOM("何文田", "Ho Man Tin"),
    HUH("紅磡", "Hung Hom"),
    ETS("尖東", "East Tsim Sha Tsui"),
    AUS("柯士甸", "Austin"),
    MEF("美孚", "Mei Foo"),
    TWW("荃灣西", "Tsuen Wan West"),
    KSR("錦上路", "Kam Sheung Road"),
    YUL("元朗", "Yuen Long"),
    LOP("朗屏", "Long Ping"),
    TIS("天水圍", "Tin Shui Wai"),
    SIH("兆康", "Siu Hong"),
    TUM("屯門", "Tuen Mun"),

    NOP("北角", "North Point"),
    QUB("鰂魚涌", "Quarry Bay"),
    YAT("油塘", "Yau Tong"),
    TIK("調景嶺", "Tiu Keng Leng"),
    TKO("將軍澳", "Tseung Kwan O"),
    HAH("坑口", "Hang Hau"),
    POA("寶琳", "Po Lam"),
    LHP("康城", "LOHAS Park"),
}
